### ISSUE TITLE
[Task]: Update Proposal Documents

### ISSUE THREAD

**Issue by lathanhthai1905** [3oak/CSC13007-GameDevCourse#8]
### Description

**Task Description**

Update proposal document following feedback and fill out remaining sections.

- [ ] Rewrite "Kỹ năng bổ trợ - Supplementary skills" section @ShurCGHung 
- [ ] Update "Concept Art" section @lathanhthai1905 
- [ ] Update "UI" section @lathanhthai1905 
- [ ] Update "Bản thiết kế kiến trúc và lập trình - Architecture Design" @HPQuyen 

**Screenshots**

_None_

### Additional Information

_None_
